name: Production deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 18

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install and Build
        run: |
          cd www
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GHPAGES_TOKEN }}
          repository-name: xkpasswd/xkpasswd.github.io
          branch: gh-pages
          folder: www/dist
          clean: true
